e2e-tests: better errors for response failures (#1442)
Replace:

```js
expect(response.ok()).toBeTruthy();
```

With:

```js
expect(response).toBeOK();
```

This changes failure messages from:

```
Error: expect: Property 'toBeOk' not found.

   at backend-client.js:69
```

To:

```http
Error: expect(response).toBeOK() failed

Call log:
→ GET http://central-dev.localhost:8989/v1/projects/9/forms/firefox_enketo_patroller/submissions/6195c3f7-785f-4825-875a-3ae57360f89e/edit
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:142.0.1) Gecko/20100101 Firefox/142.0.1
  accept: */*
  accept-encoding: gzip,deflate,br
  Authorization: Basic YWxpY2VAZXhhbXBsZS5jb206VGVzdHBhc3N3b3JkQDEyMzQ1
← 409 Conflict
  server: nginx
  date: Tue, 09 Dec 2025 10:57:52 GMT
  content-type: application/json; charset=utf-8
  content-length: 123
  connection: close
  cache-control: private, no-cache
  vary: Accept-Encoding, Origin
  etag: W/"7b-2tYcC6VCpRrSszGNo7iUNcsE+bo"
  strict-transport-security: max-age=63072000

Response text:
{"message":"The form you tried to access is not ready for web use yet. Please wait some time and try again.","code":409.11}
```