test/unit/testRequestsInclude(): improve failure message
Previously:

```
Error: an expected request was not sent
     at dist/webpack:/@getodk/central-frontend/test/util/http/common.js:82:1
     at MockHttp._executeSeries (dist/webpack:/@getodk/central-frontend/test/util/http.js:672:1)
     at MockHttp._executeSeries (dist/webpack:/@getodk/central-frontend/test/util/http.js:626:27)
```

With this change:

```
Error: an expected request was not sent: expected: [0. undefined ({ pathname, searchParams }) => {
             pathname.should.equal('/v1/projects/1/datasets/trees/entities.geojson');
             searchParams.get('$filter').split(' and ').should.eql([
               '(__system/creatorId eq 1 or __system/creatorId eq 2)',
               '__system/createdAt ge 1970-01-01T00:00:00.000Z',
               '__system/createdAt le 1970-01-02T23:59:59.999Z',
               '__system/conflict ne null'
             ]);
             searchParams.get('$search').should.equal('foo');
           } body:false], but got: [0. GET /v1/projects/1 body:false, 1. GET /v1/projects/1/datasets/trees body:false, 2. GET /v1/projects/1/datasets/trees.svc/Entities?%24top=0&%24count=true&%24filter=__system%2FdeletedAt+ne+null body:false, 3. GET /v1/projects/1/datasets/trees/entities/creators body:false, 4. GET /v1/projects/1/datasets/trees/entities.geojson?%24filter=%28__system%2FcreatorId+eq+1+or+__system%2FcreatorId+eq+2%29+and+__system%2FcreatedAt+ge+1970-01-01T00%3A00%3A00.000Z+and+__system%2FcreatedAt+lt+1970-01-03T00%3A00%3A00.000Z+and+__system%2Fconflict+ne+null&%24search=foo body:false]
     at dist/webpack:/@getodk/central-frontend/test/util/http/common.js:82:1
     at MockHttp._executeSeries (dist/webpack:/@getodk/central-frontend/test/util/http.js:672:1)
     at MockHttp._executeSeries (dist/webpack:/@getodk/central-frontend/test/util/http.js:626:27)
```