Use expect() instead of .should for props that are objects
It looks like these props are reactive proxies (isReactive() returns
`true`). Chai seems to throw an error when .should is called on a
reactive proxy, including in the cases here:

Error: Invalid Chai property: __v_isRef