transifex:destructure: improve error message for missing key
Previous:

```
TypeError: Cannot read properties of undefined (reading 'toJSON')
```

This commit:

```
Error: No value found for component.FormEditDef.action in locale "cs".
```